/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    pub fn my_windowBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_labelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_controlBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_windowFrameColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_secondaryLabelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_tertiaryLabelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_quaternaryLabelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_textColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_placeholderTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_selectedTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_textBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_selectedTextBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_keyboardFocusIndicatorColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_unemphasizedSelectedTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_unemphasizedSelectedTextBackgroundColor(
        r: *mut f64,
        g: *mut f64,
        b: *mut f64,
        a: *mut f64,
    );
}
extern "C" {
    pub fn my_linkColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_separatorColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_selectedContentBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_unemphasizedSelectedContentBackgroundColor(
        r: *mut f64,
        g: *mut f64,
        b: *mut f64,
        a: *mut f64,
    );
}
extern "C" {
    pub fn my_selectedMenuItemTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_gridColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_headerTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_controlAccentColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_controlColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_controlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_disabledControlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_selectedControlColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_selectedControlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_alternateSelectedControlTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_scrubberTexturedBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_windowFrameTextColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_underPageBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_findHighlightColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_highlightColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_shadowColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
