/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    pub fn my_windowBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_labelColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
extern "C" {
    pub fn my_controlBackgroundColor(r: *mut f64, g: *mut f64, b: *mut f64, a: *mut f64);
}
